// <auto-generated />
using System;
using EMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMS.API.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 256, DateTimeKind.Utc).AddTicks(7334),
                            PasswordHash = "$2a$11$jktJGI4pCemEIvvncmPY.O9BYGjN/ymWqMXvzM8SbKREukHBGh4/m",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(8051),
                            PasswordHash = "$2a$11$W1Fz7NA0XGp6LlM7SfHBv.cWxWeG81IRhCTvQnuomwohlztTkDu56",
                            Role = "Viewer",
                            Username = "viewer"
                        });
                });

            modelBuilder.Entity("EMS.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9001),
                            Department = "Engineering",
                            Designation = "Software Engineer",
                            Email = "harishbabu.k@gmail.com",
                            FirstName = "Harish Babu",
                            Gender = "Male",
                            JoinDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kaveri",
                            Phone = "9876543210",
                            Salary = 850000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9003)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9019),
                            Department = "Marketing",
                            Designation = "Marketing Exec",
                            Email = "balaji.m@gmail.com",
                            FirstName = "Balaji",
                            Gender = "Male",
                            JoinDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Marathi",
                            Phone = "9123456780",
                            Salary = 620000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9020)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9024),
                            Department = "HR",
                            Designation = "HR Executive",
                            Email = "harika.anam@gmail.com",
                            FirstName = "Harika",
                            Gender = "Female",
                            JoinDate = new DateTime(2019, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Anam",
                            Phone = "9876512340",
                            Salary = 550000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9024)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9027),
                            Department = "Finance",
                            Designation = "Financial Analyst",
                            Email = "poojitha.k@gmail.com",
                            FirstName = "Poojitha",
                            Gender = "Female",
                            JoinDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kaveri",
                            Phone = "9988776655",
                            Salary = 720000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9027)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9030),
                            Department = "Operations",
                            Designation = "Operations Mgr",
                            Email = "ajaykumar.p@gmail.com",
                            FirstName = "Ajay Kumar",
                            Gender = "Male",
                            JoinDate = new DateTime(2018, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Poola",
                            Phone = "9123123123",
                            Salary = 950000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9030)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9033),
                            Department = "Engineering",
                            Designation = "Senior Dev",
                            Email = "tejaswini.reddy@gmail.com",
                            FirstName = "Tejaswini",
                            Gender = "Female",
                            JoinDate = new DateTime(2017, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Reddy",
                            Phone = "9988998899",
                            Salary = 1100000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9033)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9230),
                            Department = "Marketing",
                            Designation = "Content Strategist",
                            Email = "pavankumar.m@gmail.com",
                            FirstName = "Pavan Kumar",
                            Gender = "Male",
                            JoinDate = new DateTime(2023, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Mavilla",
                            Phone = "9001002003",
                            Salary = 580000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9230)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9234),
                            Department = "Finance",
                            Designation = "Accounts Mgr",
                            Email = "tharunsangeeth.k@gmail.com",
                            FirstName = "Tharun Sangeeth",
                            Gender = "Male",
                            JoinDate = new DateTime(2020, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Katuru",
                            Phone = "9112233445",
                            Salary = 800000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9234)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9237),
                            Department = "Engineering",
                            Designation = "DevOps Eng",
                            Email = "harshitha.sree@gmail.com",
                            FirstName = "Harshitha",
                            Gender = "Female",
                            JoinDate = new DateTime(2021, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sree",
                            Phone = "9998887776",
                            Salary = 900000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9237)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9243),
                            Department = "Operations",
                            Designation = "Supply Chain Analyst",
                            Email = "vamsi.n@gmail.com",
                            FirstName = "Vamsi",
                            Gender = "Male",
                            JoinDate = new DateTime(2022, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nallamangala",
                            Phone = "9887766554",
                            Salary = 650000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9243)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9246),
                            Department = "Marketing",
                            Designation = "Brand Manager",
                            Email = "rohith.n@gmail.com",
                            FirstName = "Rohith",
                            Gender = "Male",
                            JoinDate = new DateTime(2019, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Neeli",
                            Phone = "9776655443",
                            Salary = 820000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9246)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9248),
                            Department = "Finance",
                            Designation = "Tax Consultant",
                            Email = "vamsi.krishna@gmail.com",
                            FirstName = "Vamsi",
                            Gender = "Male",
                            JoinDate = new DateTime(2021, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Krishna",
                            Phone = "9665544332",
                            Salary = 750000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9249)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9251),
                            Department = "Engineering",
                            Designation = "QA Engineer",
                            Email = "sai.vikas@gmail.com",
                            FirstName = "Sai",
                            Gender = "Male",
                            JoinDate = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Vikas",
                            Phone = "9554433221",
                            Salary = 680000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9251)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9253),
                            Department = "HR",
                            Designation = "Recruiter",
                            Email = "nandhakishore.a@gmail.com",
                            FirstName = "Nandha Kishore",
                            Gender = "Male",
                            JoinDate = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Akkineni",
                            Phone = "9443322110",
                            Salary = 500000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9253)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9270),
                            Department = "Operations",
                            Designation = "Logistics Coord",
                            Email = "laxmiprasanna.m@gmail.com",
                            FirstName = "Laxmi Prasanna",
                            Gender = "Female",
                            JoinDate = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Mandava",
                            Phone = "9332211009",
                            Salary = 540000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2026, 4, 16, 13, 38, 5, 396, DateTimeKind.Utc).AddTicks(9271)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
